"""Draw.io XML Validator - validates diagram syntax and structure."""

import re
from typing import Optional
from xml.etree import ElementTree as ET

from .models import (
    DiagramStructure,
    ValidationIssue,
    ValidationResult,
    ValidationSeverity,
)
from .parser import DrawioParser


class DrawioValidator:
    """
    Validator for Draw.io XML files.

    Checks for syntax errors, structural issues, and common problems
    in Draw.io diagrams generated by AI or other tools.
    """

    # Valid mxCell attributes
    VALID_CELL_ATTRS = {
        "id", "value", "style", "vertex", "edge", "parent",
        "source", "target", "connectable", "visible", "collapsed",
    }

    # Valid mxGeometry attributes
    VALID_GEOMETRY_ATTRS = {
        "x", "y", "width", "height", "relative", "as",
    }

    # Common shape types
    KNOWN_SHAPES = {
        "rectangle", "ellipse", "rhombus", "parallelogram", "triangle",
        "cylinder", "hexagon", "cloud", "actor", "swimlane", "process",
        "rounded", "shape", "text", "label", "image", "html",
    }

    def __init__(self):
        """Initialize the validator."""
        self._parser = DrawioParser()
        self._issues: list[ValidationIssue] = []

    def validate(self, xml_content: str) -> ValidationResult:
        """
        Validate Draw.io XML content.

        Args:
            xml_content: The raw XML content to validate

        Returns:
            ValidationResult with issues found
        """
        self._issues = []

        # Step 1: Basic XML syntax validation
        xml_valid = self._validate_xml_syntax(xml_content)
        if not xml_valid:
            return self._build_result()

        # Step 2: Draw.io structure validation
        self._validate_drawio_structure(xml_content)

        # Step 3: Parse and validate cells
        try:
            structure = self._parser.parse(xml_content)
            self._validate_cells(structure)
            self._validate_edges(structure)
            self._validate_styles(structure)
            self._validate_geometry(structure)
        except ValueError as e:
            self._add_issue(
                ValidationSeverity.ERROR,
                "PARSE_ERROR",
                str(e),
                suggestion="Check the XML structure matches Draw.io format",
            )

        return self._build_result()

    def _validate_xml_syntax(self, xml_content: str) -> bool:
        """Validate basic XML syntax."""
        try:
            ET.fromstring(xml_content.strip())
            return True
        except ET.ParseError as e:
            # Extract line and column from error
            line, col = None, None
            error_msg = str(e)
            match = re.search(r"line (\d+), column (\d+)", error_msg)
            if match:
                line = int(match.group(1))
                col = int(match.group(2))

            self._add_issue(
                ValidationSeverity.ERROR,
                "XML_SYNTAX_ERROR",
                f"XML syntax error: {error_msg}",
                line=line,
                column=col,
                suggestion="Check for unclosed tags, invalid characters, or encoding issues",
            )
            return False

    def _validate_drawio_structure(self, xml_content: str) -> None:
        """Validate Draw.io specific structure."""
        root = ET.fromstring(xml_content.strip())

        # Check root element
        if root.tag not in ("mxfile", "mxGraphModel"):
            self._add_issue(
                ValidationSeverity.ERROR,
                "INVALID_ROOT",
                f"Invalid root element '{root.tag}', expected 'mxfile' or 'mxGraphModel'",
                element=root.tag,
                suggestion="Draw.io files must start with <mxfile> or <mxGraphModel>",
            )
            return

        if root.tag == "mxfile":
            # Check for at least one diagram
            diagrams = root.findall("diagram")
            if not diagrams:
                self._add_issue(
                    ValidationSeverity.ERROR,
                    "NO_DIAGRAM",
                    "No <diagram> element found in mxfile",
                    suggestion="Add at least one <diagram> element containing the graph model",
                )
                return

            for diagram in diagrams:
                self._validate_diagram_element(diagram)

        elif root.tag == "mxGraphModel":
            self._validate_graph_model(root)

    def _validate_diagram_element(self, diagram: ET.Element) -> None:
        """Validate a diagram element."""
        # Check for id attribute
        if not diagram.get("id"):
            self._add_issue(
                ValidationSeverity.WARNING,
                "MISSING_DIAGRAM_ID",
                "Diagram element missing 'id' attribute",
                element="diagram",
                suggestion="Add an 'id' attribute to the diagram element",
            )

        # Check for mxGraphModel or compressed content
        mxgraph = diagram.find("mxGraphModel")
        text_content = (diagram.text or "").strip()

        if mxgraph is None and not text_content:
            self._add_issue(
                ValidationSeverity.ERROR,
                "EMPTY_DIAGRAM",
                "Diagram has no content (no mxGraphModel or compressed data)",
                element="diagram",
                suggestion="Add <mxGraphModel> element or compressed diagram data",
            )
        elif mxgraph is not None:
            self._validate_graph_model(mxgraph)

    def _validate_graph_model(self, model: ET.Element) -> None:
        """Validate an mxGraphModel element."""
        root_elem = model.find("root")
        if root_elem is None:
            self._add_issue(
                ValidationSeverity.ERROR,
                "MISSING_ROOT",
                "mxGraphModel missing <root> element",
                element="mxGraphModel",
                suggestion="Add a <root> element containing mxCell elements",
            )
            return

        # Check for required root cells (0 and 1)
        cell_ids = {cell.get("id") for cell in root_elem.findall("mxCell")}
        obj_ids = {obj.get("id") for obj in root_elem.findall("object")}
        all_ids = cell_ids | obj_ids

        if "0" not in all_ids:
            self._add_issue(
                ValidationSeverity.ERROR,
                "MISSING_ROOT_CELL",
                "Missing root cell with id='0'",
                suggestion='Add <mxCell id="0"/> as the diagram root',
            )

        if "1" not in all_ids:
            self._add_issue(
                ValidationSeverity.ERROR,
                "MISSING_DEFAULT_PARENT",
                "Missing default parent cell with id='1'",
                suggestion='Add <mxCell id="1" parent="0"/> as the default parent',
            )

    def _validate_cells(self, structure: DiagramStructure) -> None:
        """Validate all cells in the diagram."""
        for page in structure.pages:
            cell_ids = {cell.id for cell in page.cells}

            for cell in page.cells:
                # Check for empty id
                if not cell.id:
                    self._add_issue(
                        ValidationSeverity.ERROR,
                        "EMPTY_CELL_ID",
                        "Cell has empty or missing 'id' attribute",
                        suggestion="Every mxCell must have a unique 'id' attribute",
                    )

                # Check parent reference
                if cell.parent and cell.parent not in cell_ids:
                    if cell.parent != "0":  # 0 is the implicit root
                        self._add_issue(
                            ValidationSeverity.ERROR,
                            "INVALID_PARENT",
                            f"Cell '{cell.id}' references non-existent parent '{cell.parent}'",
                            element=cell.id,
                            suggestion=f"Ensure parent cell '{cell.parent}' exists",
                        )

    def _validate_edges(self, structure: DiagramStructure) -> None:
        """Validate edge connections."""
        for page in structure.pages:
            cell_ids = {cell.id for cell in page.cells}

            for cell in page.cells:
                if not cell.is_edge:
                    continue

                # Check source reference
                if cell.source and cell.source not in cell_ids:
                    self._add_issue(
                        ValidationSeverity.ERROR,
                        "INVALID_EDGE_SOURCE",
                        f"Edge '{cell.id}' references non-existent source '{cell.source}'",
                        element=cell.id,
                        suggestion=f"Ensure source cell '{cell.source}' exists",
                    )

                # Check target reference
                if cell.target and cell.target not in cell_ids:
                    self._add_issue(
                        ValidationSeverity.ERROR,
                        "INVALID_EDGE_TARGET",
                        f"Edge '{cell.id}' references non-existent target '{cell.target}'",
                        element=cell.id,
                        suggestion=f"Ensure target cell '{cell.target}' exists",
                    )

                # Warning for edge without source or target
                if not cell.source and not cell.target:
                    self._add_issue(
                        ValidationSeverity.WARNING,
                        "FLOATING_EDGE",
                        f"Edge '{cell.id}' has no source or target connection",
                        element=cell.id,
                        suggestion="Edges should connect to source and/or target cells",
                    )

    def _validate_styles(self, structure: DiagramStructure) -> None:
        """Validate cell styles."""
        for page in structure.pages:
            for cell in page.cells:
                if not cell.style:
                    continue

                # Check for malformed style string
                raw = cell.style.raw
                if raw and not self._is_valid_style_format(raw):
                    self._add_issue(
                        ValidationSeverity.WARNING,
                        "MALFORMED_STYLE",
                        f"Cell '{cell.id}' has potentially malformed style string",
                        element=cell.id,
                        suggestion="Style should be semicolon-separated key=value pairs",
                    )

                # Check for common style issues
                if cell.is_vertex and "edgeStyle" in cell.style.properties:
                    self._add_issue(
                        ValidationSeverity.WARNING,
                        "VERTEX_WITH_EDGE_STYLE",
                        f"Vertex '{cell.id}' has edgeStyle property (usually for edges)",
                        element=cell.id,
                    )

    def _validate_geometry(self, structure: DiagramStructure) -> None:
        """Validate cell geometry."""
        for page in structure.pages:
            for cell in page.cells:
                if not cell.geometry:
                    continue

                geom = cell.geometry

                # Check for negative dimensions
                if geom.width is not None and geom.width < 0:
                    self._add_issue(
                        ValidationSeverity.ERROR,
                        "NEGATIVE_WIDTH",
                        f"Cell '{cell.id}' has negative width: {geom.width}",
                        element=cell.id,
                        suggestion="Width must be a non-negative number",
                    )

                if geom.height is not None and geom.height < 0:
                    self._add_issue(
                        ValidationSeverity.ERROR,
                        "NEGATIVE_HEIGHT",
                        f"Cell '{cell.id}' has negative height: {geom.height}",
                        element=cell.id,
                        suggestion="Height must be a non-negative number",
                    )

                # Warning for zero-size vertices
                if cell.is_vertex:
                    if geom.width == 0 and geom.height == 0:
                        self._add_issue(
                            ValidationSeverity.WARNING,
                            "ZERO_SIZE_VERTEX",
                            f"Vertex '{cell.id}' has zero width and height",
                            element=cell.id,
                            suggestion="Vertices typically need positive dimensions",
                        )

    def _is_valid_style_format(self, style: str) -> bool:
        """Check if style string has valid format."""
        if not style:
            return True
        # Basic validation: should be semicolon-separated
        # Each part should be either a flag or key=value
        parts = style.split(";")
        for part in parts:
            part = part.strip()
            if not part:
                continue
            # Check for obvious issues like unclosed brackets
            if part.count("(") != part.count(")"):
                return False
            if part.count("[") != part.count("]"):
                return False
        return True

    def _add_issue(
        self,
        severity: ValidationSeverity,
        code: str,
        message: str,
        line: Optional[int] = None,
        column: Optional[int] = None,
        element: Optional[str] = None,
        suggestion: Optional[str] = None,
    ) -> None:
        """Add a validation issue."""
        self._issues.append(
            ValidationIssue(
                severity=severity,
                code=code,
                message=message,
                line=line,
                column=column,
                element=element,
                suggestion=suggestion,
            )
        )

    def _build_result(self) -> ValidationResult:
        """Build the final validation result."""
        error_count = sum(
            1 for i in self._issues if i.severity == ValidationSeverity.ERROR
        )
        warning_count = sum(
            1 for i in self._issues if i.severity == ValidationSeverity.WARNING
        )

        return ValidationResult(
            valid=error_count == 0,
            issues=self._issues,
            error_count=error_count,
            warning_count=warning_count,
        )
